# Display Robot
print("###########")
print("#")      ("#")
print("#")      ("#")
print("###########")
print("#")      ("#")
print("#")      ("#")
print("###########")
print("#")      ("#")
print("#")      ("#")
print("#")      ("#")
print("#")      ("#")